### ISSUE TITLE
checklist css broke

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout-plugins-py#36]
```
- [ ] oi
- [ ] teste
- [x] done
```

![image](https://user-images.githubusercontent.com/1039615/207684964-1675f7d8-215f-4f73-acba-5310d7baced0.png)

**Comment by toshikurauchi** [comment]
@rafaelcorsi você verifica se a versão atual resolveu isso, por favor?

**Comment by rafaelcorsi** [comment]
resolveu! vlw
