### ISSUE TITLE
improve tabs inside tabs 

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout-plugins-py#42]
I can't tell just by looking which one is selected: C or C++

![image](https://user-images.githubusercontent.com/1039615/207824444-c6ee8450-f5eb-45f1-9541-39dd94869b46.png)

**Comment by toshikurauchi** [comment]
@rafaelcorsi você verifica se a versão atual resolveu isso, por favor?

**Comment by rafaelcorsi** [comment]
gostei! vlw

![image](https://user-images.githubusercontent.com/1039615/211339842-1df0d127-f7cc-4e67-956c-68e4fef2bd25.png)
