### ISSUE TITLE
improve table  render

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout-plugins-py#57]
```
| Item         | Price     | # In stock |
|--------------|-----------|------------|
| Juicy Apples | 1.99      | *7*        |
| Bananas      | **1.89**  | 5234       |
```

tables does not look that it is a table:

![image](https://user-images.githubusercontent.com/1039615/210656940-62bd307c-031a-433e-b73f-64a4fac6e183.png)

- add horizontal and vertical lines?

**Comment by toshikurauchi** [comment]
@rafaelcorsi você verifica se a versão atual resolveu isso, por favor?

**Comment by rafaelcorsi** [comment]
resolveu!
